version: '3'
services:
  postgres:
    image: postgres:15.2-alpine
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - local


  keycloak:
    image: quay.io/keycloak/keycloak:22.0.4
    command: start-dev
    restart: always
    links:
      - postgres
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: 4)tHhU@tVxsd5Prh
      KC_DB: postgres
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_HOSTNAME_STRICT_HTTPS: 'false'
    networks:
      - local
networks:
  local:
